# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a92396fa1e262f38eaed8af2704597e0"
name = "qr-generator"
handle = "qr-generator-18"
application_url = "https://cake-glen-dictionaries-carey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jigme-store-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cake-glen-dictionaries-carey.trycloudflare.com/auth/callback",
  "https://cake-glen-dictionaries-carey.trycloudflare.com/auth/shopify/callback",
  "https://cake-glen-dictionaries-carey.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
